package com.quiz.servlet;
import com.quiz.dao.*; import com.quiz.model.*; import java.io.*; import java.sql.SQLException; import java.util.*; import javax.servlet.*; import javax.servlet.annotation.WebServlet; import javax.servlet.http.*;
@WebServlet("/teacher/dashboard")
public class TeacherDashboardServlet extends HttpServlet {
 private final QuizDAO quizDAO=new QuizDAO(); private final QuestionDAO questionDAO=new QuestionDAO();
 protected void doGet(HttpServletRequest req,HttpServletResponse resp)throws ServletException,IOException { User u=(User)req.getSession().getAttribute("user"); try { String edit=req.getParameter("edit"); if(edit!=null)try{Quiz q=quizDAO.findByIdAndTeacher(Integer.parseInt(edit),u.getId());req.setAttribute("editing",q);if(q!=null){List<Integer> ids=new ArrayList<>();for(Question x:quizDAO.findQuestions(q.getId()))ids.add(x.getId());req.setAttribute("selectedIds",ids);}}catch(NumberFormatException ignored){} req.setAttribute("quizzes",quizDAO.findByTeacher(u.getId()));req.setAttribute("questions",questionDAO.findAll());req.getRequestDispatcher("/WEB-INF/views/teacher-dashboard.jsp").forward(req,resp); }catch(SQLException e){throw new ServletException("Could not load dashboard",e);} }
 protected void doPost(HttpServletRequest req,HttpServletResponse resp)throws ServletException,IOException { User u=(User)req.getSession().getAttribute("user");String action=req.getParameter("action");try {int id=parse(req.getParameter("id"),0);if("delete".equals(action)){quizDAO.delete(id,u.getId());redirect(resp,req,"Assessment deleted");return;}if("toggle".equals(action)){quizDAO.setPublished(id,u.getId(),"true".equals(req.getParameter("published")));redirect(resp,req,"Publication status updated");return;} Quiz q=new Quiz();q.setId(id);q.setTeacherId(u.getId());q.setSubject(clean(req.getParameter("subject")));q.setTitle(clean(req.getParameter("title")));q.setDescription(clean(req.getParameter("description")));q.setQuizType("EXAM".equals(req.getParameter("quizType"))?"EXAM":"PRACTICE");q.setDurationMinutes(parse(req.getParameter("durationMinutes"),0));q.setPassingPercentage(parse(req.getParameter("passingPercentage"),-1));q.setPublished(req.getParameter("published")!=null);List<Integer> ids=new ArrayList<>();String[] raw=req.getParameterValues("questionId");if(raw!=null)for(String x:raw){int v=parse(x,0);if(v>0)ids.add(v);} if(q.getSubject().isEmpty()||q.getTitle().isEmpty()||q.getDurationMinutes()<1||q.getPassingPercentage()<0||q.getPassingPercentage()>100||ids.isEmpty()){req.setAttribute("error","Enter a subject, title, valid duration/pass percentage, and choose at least one question.");req.setAttribute("editing",q);req.setAttribute("selectedIds",ids);req.setAttribute("quizzes",quizDAO.findByTeacher(u.getId()));req.setAttribute("questions",questionDAO.findAll());req.getRequestDispatcher("/WEB-INF/views/teacher-dashboard.jsp").forward(req,resp);return;}quizDAO.save(q,ids);redirect(resp,req,id==0?"Assessment created":"Assessment updated");}catch(SQLException e){throw new ServletException("Could not save assessment",e);} }
 private static int parse(String v,int d){try{return Integer.parseInt(v);}catch(Exception e){return d;}} private static String clean(String s){return s==null?"":s.trim();} private static void redirect(HttpServletResponse p,HttpServletRequest r,String m)throws IOException{p.sendRedirect(r.getContextPath()+"/teacher/dashboard?msg="+java.net.URLEncoder.encode(m,"UTF-8"));}
}
