<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<c:set var="pageTitle" value="Teacher Dashboard"/><%@ include file="_header.jspf" %>
<h1>Teacher Dashboard</h1>
<c:if test="${not empty param.msg}"><p class="notice ok"><c:out value="${param.msg}"/></p></c:if><c:if test="${not empty error}"><p class="notice bad"><c:out value="${error}"/></p></c:if>
<section class="card"><h2>${not empty editing ? 'Edit assessment' : 'Create assessment'}</h2><form method="post" action="${pageContext.request.contextPath}/teacher/dashboard"><input type="hidden" name="id" value="${editing.id}"><label>Subject</label><input name="subject" required placeholder="e.g. Java" value="<c:out value='${editing.subject}'/>"><label>Title</label><input name="title" required value="<c:out value='${editing.title}'/>"><label>Description</label><textarea name="description" rows="2"><c:out value="${editing.description}"/></textarea><div class="grid2"><div><label>Type</label><select name="quizType"><option value="PRACTICE" ${editing.quizType != 'EXAM' ? 'selected' : ''}>PRACTICE</option><option value="EXAM" ${editing.quizType == 'EXAM' ? 'selected' : ''}>EXAM</option></select></div><div><label>Duration (minutes)</label><input name="durationMinutes" type="number" min="1" required value="${empty editing ? 10 : editing.durationMinutes}"></div><div><label>Passing percentage</label><input name="passingPercentage" type="number" min="0" max="100" required value="${empty editing ? 50 : editing.passingPercentage}"></div></div><label><input type="checkbox" name="published" ${editing.published ? 'checked' : ''}> Publish now</label><h3>Select questions</h3><div class="question-picker"><c:forEach var="q" items="${questions}"><label class="pick"><input type="checkbox" name="questionId" value="${q.id}" ${selectedIds.contains(q.id) ? 'checked' : ''}> <strong>#${q.id}</strong> <c:out value="${q.questionText}"/></label></c:forEach></div><button class="btn" type="submit">Save assessment</button></form></section>
<h2>Your assessments</h2><c:choose><c:when test="${empty quizzes}"><p class="muted">Create your first assessment above.</p></c:when><c:otherwise><table><thead><tr><th>Subject</th><th>Title</th><th>Type</th><th>Questions</th><th>Status</th><th></th></tr></thead><tbody><c:forEach var="q" items="${quizzes}"><tr><td><c:out value="${q.subject}"/></td><td><strong><c:out value="${q.title}"/></strong></td><td>${q.quizType}</td><td>${q.questionCount}</td><td>${q.published ? 'Published' : 'Draft'}</td><td class="actions"><a href="${pageContext.request.contextPath}/teacher/dashboard?edit=${q.id}">Edit</a> <a href="${pageContext.request.contextPath}/teacher/results?quizId=${q.id}">Results</a></td></tr></c:forEach></tbody></table></c:otherwise></c:choose>
<p><a class="btn ghost" href="${pageContext.request.contextPath}/admin/questions">Manage question bank</a> <a class="btn ghost" href="${pageContext.request.contextPath}/teacher/notifications">Notifications</a></p>
<%@ include file="_footer.jspf" %>
